# Generated by Django 4.1.1 on 2022-09-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='image',
            field=models.ImageField(default=1, max_length=511, upload_to='ads'),
            preserve_default=False,
        ),
    ]
