# Generated by Django 4.1.1 on 2022-09-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ads_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='image',
            field=models.ImageField(max_length=511, upload_to='ads/media'),
        ),
    ]
