# Generated by Django 4.1.1 on 2022-09-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='no',
            new_name='number',
        ),
    ]
